#!/usr/bin/env python3
"""
代码型 Agent

负责代码编写、调试和优化
"""

import logging
from typing import Any, Dict, Optional

from .base_agent import BaseAgent

logger = logging.getLogger(__name__)


class CodeAgent(BaseAgent):
    """
    代码型 Agent
    
    擅长：
    - 代码编写和生成
    - 代码调试和修复
    - 代码重构和优化
    - 测试用例生成
    """
    
    def __init__(self, name: str = "code", config: Optional[Dict] = None):
        super().__init__(
            name=name,
            description="代码型 Agent，负责代码编写和调试",
            config=config
        )
        self.add_skill("code_write")
        self.add_skill("code_debug")
        self.add_skill("code_review")
        self.add_skill("test_generation")
        self.language = config.get("language", "python") if config else "python"
    
    async def execute(self, task: str, context: Optional[Dict] = None) -> Dict[str, Any]:
        """
        执行代码任务
        
        工作流程：
        1. 分析代码需求
        2. 设计实现方案
        3. 编写代码
        4. 测试验证
        5. 优化完善
        """
        context = context or {}
        
        logger.info(f"代码 Agent 开始任务: {task[:100]}...")
        
        # 步骤 1: 分析需求
        requirements = self._analyze_requirements(task)
        
        # 步骤 2: 设计方案
        design = self._design_solution(requirements)
        
        # 步骤 3: 编写代码
        code = self._write_code(design)
        
        # 步骤 4: 测试验证
        test_results = await self._run_tests(code)
        
        # 步骤 5: 优化
        if not test_results["passed"]:
            code = self._fix_code(code, test_results["errors"])
            test_results = await self._run_tests(code)
        
        return {
            "success": test_results["passed"],
            "task": task,
            "requirements": requirements,
            "design": design,
            "code": code,
            "test_results": test_results,
            "language": self.language
        }
    
    def _analyze_requirements(self, task: str) -> Dict:
        """分析代码需求"""
        # 检测编程语言
        languages = {
            "python": ["python", "py"],
            "javascript": ["javascript", "js", "node"],
            "typescript": ["typescript", "ts"],
            "java": ["java"],
            "go": ["go", "golang"],
            "rust": ["rust", "rs"],
            "cpp": ["c++", "cpp", "cxx"]
        }
        
        task_lower = task.lower()
        detected_lang = self.language
        for lang, keywords in languages.items():
            if any(kw in task_lower for kw in keywords):
                detected_lang = lang
                break
        
        self.language = detected_lang
        
        return {
            "language": detected_lang,
            "features": self._extract_features(task),
            "constraints": self._extract_constraints(task)
        }
    
    def _extract_features(self, task: str) -> list:
        """提取功能需求"""
        features = []
        keywords = ["实现", "添加", "支持", "创建", "编写"]
        for kw in keywords:
            if kw in task:
                # 简单提取关键词后面的内容
                idx = task.find(kw)
                if idx >= 0:
                    feature = task[idx:idx+50].strip()
                    features.append(feature)
        return features or ["实现核心功能"]
    
    def _extract_constraints(self, task: str) -> list:
        """提取约束条件"""
        constraints = []
        if "性能" in task:
            constraints.append("性能优化")
        if "线程安全" in task or "并发" in task:
            constraints.append("线程安全")
        if "内存" in task:
            constraints.append("内存优化")
        return constraints or ["代码清晰可读"]
    
    def _design_solution(self, requirements: Dict) -> Dict:
        """设计方案"""
        return {
            "architecture": f"{requirements['language']} 模块设计",
            "modules": ["核心逻辑", "工具函数", "错误处理"],
            "interfaces": ["输入处理", "输出格式化"],
            "dependencies": self._get_dependencies(requirements["language"])
        }
    
    def _get_dependencies(self, language: str) -> list:
        """获取常用依赖"""
        deps = {
            "python": ["typing", "logging", "pathlib"],
            "javascript": ["lodash", "axios"],
            "typescript": ["@types/node"],
            "java": ["lombok", "guava"],
            "go": ["context", "fmt"],
            "rust": ["serde", "tokio"]
        }
        return deps.get(language, [])
    
    def _write_code(self, design: Dict) -> str:
        """编写代码"""
        # 模拟代码生成
        code = f"""// {design['architecture']}
// Auto-generated by CodeAgent

class Solution {{
    constructor() {{
        this.initialized = true;
    }}
    
    async process(input) {{
        // 核心逻辑
        const result = await this.handle(input);
        return this.format(result);
    }}
    
    async handle(input) {{
        // TODO: 实现处理逻辑
        return input;
    }}
    
    format(result) {{
        return {{
            success: true,
            data: result
        }};
    }}
}}

module.exports = Solution;
"""
        return code
    
    async def _run_tests(self, code: str) -> Dict:
        """运行测试"""
        # 模拟测试
        return {
            "passed": True,
            "tests_run": 5,
            "tests_passed": 5,
            "errors": [],
            "coverage": 85.0
        }
    
    def _fix_code(self, code: str, errors: list) -> str:
        """修复代码"""
        # 模拟代码修复
        return code + "\n// Fixed errors: " + str(errors)
